sonar.projectKey=Calculator
sonar.projectName=Calculator
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
sonar.host.url=http://localhost:9000/
sonar.token=squ_0e28cd44b0e43d5bdf8f7953af00eee33e4b0ede